#load markers and data
datafile = "D:/UPitts/Research/cytof/data/"
setwd(datafile)

library(flowCore)
dt<-read.FCS("downsample.fcs",transformation = FALSE)
load("ref_label.Rdata")
markers<- attributes(ref_label)$markers$name
dt2<-dt[,markers]
#transformation
asinhTrans=arcsinhTransform(a=0, b=0.2)
translist<-transformList(markers, asinhTrans)
dt2.transform<-transform(dt2, translist)
dt2.transform<-exprs(dt2.transform)
desc = attributes(ref_label)$markers$desc
desc2 = sub("[0-9]*[A-Za-z]*_(.*)", "\\1", desc)
dt2.transform = as.data.frame(dt2.transform)
colnames(dt2.transform) = desc2
# standardize = function(gene.i){
#   x = as.numeric(gene.i)
#   names(x) = names(gene.i)
#   s.x = (x-mean(x))/sd(x)
#   s.x[which(s.x>2)] = 2
#   s.x[which(s.x<(-2))] = -2
#   return(s.x)
# }

#ACCENSE
#load cluster labels
label = read.csv("D:/UPitts/Research/cytof/accense/accense_output.csv")
#label = read.csv("D:/CyTof_review_Xiangning/flowgrid/out.csv")
label$population = as.factor(label$population)
cluster_label = label$population

# #rearrange: put samples in the same cluster together
# order_label = order(cluster_label$cluster_label)
# cluster_label_ordered = as.data.frame(cluster_label[order_label, ])
# colnames(cluster_label_ordered) = "cluster_label"
# dt2.ordered = dt2.transform[order_label, ]

#calculate the mean expression for each cluster
dt.split = split(dt2.transform, cluster_label)
dt.split.mean = lapply(dt.split, function(x){apply(x, 2, mean, na.rm = TRUE)})
dt.mean = plyr::ldply(dt.split.mean, rbind)[, -1]

#test subset
# sample = sample(1:nrow(dt2.ordered), 200)
# sample_order = sample[order(sample)]
# dt2.sub = dt2.ordered[sample_order, ]
# label.sub = as.data.frame(cluster_label_ordered[sample_order, ])
# colnames(label.sub) = "cluster_label"
# nlevels_sub = nlevels(label.sub$cluster_label)
# 
# colors = distinctColorPalette(k = nlevels_sub, altCol = FALSE, runTsne = FALSE)
# x = aheatmap(t(dt2.sub), annCol = label.sub, annColors = list(colors),
#          Rowv = NA, Colv = NA, main = "Heatmap of Stardarized log2CPM of \n 50 top Differentially Expressed Genes in DLPFC", 
#          color = "YlGnBu", #breaks = c(-2, seq(-1, 1, length.out = 9),  2), 
#          cexRow = 1.2)

library(NMF)
#install.packages("randomcoloR")
library(randomcoloR)
cluster_label = as.data.frame(list(cluster_label = c(1:nrow(dt.mean))))
pdf("ACCENSE_heatmap2.pdf", width = 10, height = 10, onefile = FALSE)
colors = distinctColorPalette(k = nrow(dt.mean), altCol = FALSE, runTsne = FALSE)
aheatmap(as.matrix(t(dt.mean)),annCol = cluster_label, annColors = list(colors),annLegend = FALSE,
         Rowv = NA, Colv = NA, main = paste0("Heatmap of clusters generated by ACCENSE \n Number of clusters = ", nrow(dt.mean)), 
         color = "YlGnBu", 
         cexRow = 1.2)
dev.off()

#DensVM
load("D:/UPitts/Research/cytof/cytofkit/densVMresult1.rData")
cluster_label<-cluster_DensVM[["clusters"]]$cluster

dt.split = split(dt2.transform, cluster_label)
dt.split.mean = lapply(dt.split, function(x){apply(x, 2, mean, na.rm = TRUE)})
dt.mean = plyr::ldply(dt.split.mean, rbind)[, -1]

cluster_label = as.data.frame(list(cluster_label = c(1:nrow(dt.mean))))
pdf("DensVM_heatmap2.pdf", width = 10, height = 10, onefile = FALSE)
colors = distinctColorPalette(k = nrow(dt.mean), altCol = FALSE, runTsne = FALSE)
aheatmap(as.matrix(t(dt.mean)),annCol = cluster_label, annColors = list(colors),annLegend = FALSE,
         Rowv = NA, Colv = NA, main = paste0("Heatmap of clusters generated by DensVM \n Number of clusters = ", nrow(dt.mean)), 
         color = "YlGnBu", 
         cexRow = 1.2)
dev.off()






